name: lane_det
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - opencv-python
      - numpy
      - scipy
      - onnxruntime
      - gdown
